import React, { useState, useEffect } from 'react';
import { Scan, User } from '../types';
import { getScans, saveScan, generateCaseId } from '../services/storage';
import { AIAnalysisResult, analyzeMRI } from '../services/geminiService';
import HeatmapOverlay from '../components/HeatmapOverlay';
import HeatmapLegendCard from '../components/HeatmapLegendCard';
import ResultSummaryCard from '../components/ResultSummaryCard';
import ClinicalDisclaimer from '../components/ClinicalDisclaimer';

interface Props {
  user: User;
}

const ALLOWED_TYPES = ['image/jpeg', 'image/png'];
const MAX_FILE_MB = 10;

const FieldError: React.FC<{ msg?: string }> = ({ msg }) =>
  msg ? <p className="text-red-500 text-xs font-bold mt-1 ml-1">⚠ {msg}</p> : null;

const PatientPortal: React.FC<Props> = ({ user }) => {
  const [scans, setScans] = useState<Scan[]>([]);
  const [selectedImage, setSelectedImage] = useState<string | null>(null);
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [result, setResult] = useState<AIAnalysisResult & { caseId?: string } | null>(null);
  const [showHeatmap, setShowHeatmap] = useState(true);
  const [fileError, setFileError] = useState<string | undefined>();
  const [submitError, setSubmitError] = useState<string | undefined>();

  useEffect(() => {
    setScans(getScans().filter(s => s.patientId === user.id));
  }, [user.id]);

  const handleFileChange = (file: File | undefined) => {
    setFileError(undefined);
    setResult(null);
    setSubmitError(undefined);
    if (!file) return;
    if (!ALLOWED_TYPES.includes(file.type)) {
      setFileError('Only JPG and PNG files are supported');
      return;
    }
    if (file.size > MAX_FILE_MB * 1024 * 1024) {
      setFileError(`File too large. Maximum size is ${MAX_FILE_MB}MB`);
      return;
    }
    setSelectedFile(file);
    const reader = new FileReader();
    reader.onload = (ev) => setSelectedImage(ev.target?.result as string);
    reader.readAsDataURL(file);
  };

  const handleDownloadReport = (scan: any) => {
    const reportContent = `
TUMORNOT MEDICAL SYSTEMS - FORMAL DIAGNOSTIC REPORT
====================================================
Case Reference : ${scan.caseId || scan.case_id || 'N/A'}
Date           : ${new Date().toLocaleString()}
Patient        : ${user.name} (ID: ${user.id})

DIAGNOSTIC SUMMARY
------------------
Prediction     : ${scan.prediction}
Confidence     : ${scan.confidence}%
Risk Level     : ${scan.risk_level || (scan.prediction === 'Tumor' ? (scan.confidence >= 85 ? 'HIGH' : 'MODERATE') : 'LOW')}

CLINICAL RATIONALE
------------------
${scan.explanation}

DISCLAIMER
----------
This is an AI-assisted analysis generated by the TumORnot System.
Final diagnosis must always be confirmed by a qualified medical
professional or board-certified radiologist.
    `.trim();

    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `TumORnot_Report_${scan.caseId || scan.case_id || 'Scan'}.txt`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const runAnalysis = async () => {
    setSubmitError(undefined);
    if (!selectedFile || !selectedImage) {
      setFileError('Please upload an MRI scan image before running analysis');
      return;
    }

    setIsAnalyzing(true);
    setResult(null);

    try {
      const analysis = await analyzeMRI(selectedFile);
      const caseId = generateCaseId();
      setResult({ ...analysis, caseId });

      const newScan: Scan = {
        id: 'PT_' + Math.random().toString(36).substr(2, 6).toUpperCase(),
        caseId,
        patientId: user.id,
        mriUrl: selectedImage,
        prediction: analysis.prediction,
        confidence: analysis.confidence,
        date: new Date().toISOString(),
        explanation: analysis.explanation,
        roi: analysis.roi,
        isEmergency: analysis.prediction === 'Tumor' && analysis.confidence > 90,
      };
      saveScan(newScan);
      setScans(prev => [newScan, ...prev]);

    } catch (error: any) {
      console.error('Analysis error:', error);
      setSubmitError(
        error?.message?.includes('fetch')
          ? 'Cannot reach backend. Make sure it is running at localhost:8000.'
          : `Analysis failed: ${error?.message || 'Unknown error'}`
      );
    } finally {
      setIsAnalyzing(false);
    }
  };

  const resetScan = () => {
    setSelectedImage(null);
    setSelectedFile(null);
    setResult(null);
    setFileError(undefined);
    setSubmitError(undefined);
  };

  return (
    <div className="space-y-12 pb-20">

      {/* ── INTAKE PANEL ── */}
      <div className="bg-white rounded-[3rem] p-10 shadow-sm border border-gray-100">
        <h2 className="text-3xl font-black mb-2 text-gray-800">Neurological Intake</h2>
        <p className="text-sm text-gray-400 mb-8 font-medium">Upload your MRI scan for AI-assisted analysis</p>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12">

          {/* LEFT — controls */}
          <div className="space-y-6">

            {/* Upload zone */}
            <div>
              <label className="text-xs font-black uppercase tracking-widest text-gray-500 mb-2 block">
                MRI Scan Image *
              </label>
              <div
                className={`border-4 border-dashed rounded-[2.5rem] p-10 flex flex-col items-center justify-center cursor-pointer transition group ${
                  fileError
                    ? 'border-red-400 bg-red-50'
                    : selectedFile
                    ? 'border-green-400 bg-green-50/30'
                    : 'border-gray-100 bg-gray-50/50 hover:bg-gray-50'
                }`}
                onClick={() => document.getElementById('mri-upload-patient')?.click()}
              >
                <input
                  type="file"
                  id="mri-upload-patient"
                  className="hidden"
                  accept=".jpg,.jpeg,.png"
                  onChange={(e) => handleFileChange(e.target.files?.[0])}
                />
                <div className={`p-6 rounded-full mb-4 group-hover:scale-110 transition ${
                  fileError ? 'bg-red-100 text-red-500' : 'bg-burgundy/10 text-burgundy'
                }`}>
                  <svg className="w-10 h-10" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2"
                      d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
                  </svg>
                </div>
                {selectedFile ? (
                  <>
                    <span className="font-black text-green-700">✅ {selectedFile.name}</span>
                    <p className="text-xs text-green-500 mt-1">{(selectedFile.size / 1024).toFixed(0)} KB — click to change</p>
                  </>
                ) : (
                  <>
                    <span className="font-black text-lg text-gray-800">Upload MRI Scan</span>
                    <p className="text-sm text-gray-400 mt-2">JPG or PNG, max 10MB</p>
                  </>
                )}
              </div>
              <FieldError msg={fileError} />
            </div>

            {/* Submit error */}
            {submitError && (
              <div className="bg-red-50 border-2 border-red-200 rounded-xl p-4">
                <p className="text-red-600 text-sm font-bold">⚠ {submitError}</p>
              </div>
            )}

            {/* Action buttons */}
            {selectedImage && (
              <div className="flex gap-3">
                <button
                  onClick={runAnalysis}
                  disabled={isAnalyzing || !!fileError}
                  className="flex-1 py-5 bg-burgundy text-white font-black rounded-[1.5rem] shadow-xl hover:shadow-2xl transition disabled:opacity-50 uppercase tracking-widest text-sm"
                >
                  {isAnalyzing ? '⏳ ANALYSING...' : '🧠 INITIATE AI ANALYSIS'}
                </button>
                <button
                  onClick={resetScan}
                  className="px-5 py-5 border-2 border-gray-200 text-gray-500 rounded-[1.5rem] font-black text-sm hover:bg-gray-50 transition"
                  title="Clear"
                >
                  ✕
                </button>
              </div>
            )}

            {result && <HeatmapLegendCard />}
          </div>

          {/* RIGHT — MRI viewer */}
          <div className="flex flex-col items-center">
            <div className="relative rounded-[2.5rem] overflow-hidden bg-black aspect-square w-full flex items-center justify-center border-8 border-white shadow-2xl">
              {selectedImage ? (
                <>
                  <img src={selectedImage} className="max-w-full max-h-full object-contain" alt="MRI Scan" />
                  {result && <HeatmapOverlay roi={result.roi} isVisible={showHeatmap} />}
                  {result && (
                    <button
                      onClick={() => setShowHeatmap(!showHeatmap)}
                      className="absolute top-6 right-6 bg-white/95 backdrop-blur px-4 py-2 rounded-full text-xs font-black text-burgundy shadow-xl z-10"
                    >
                      {showHeatmap ? 'HIDE GRAD-CAM' : 'VIEW GRAD-CAM'}
                    </button>
                  )}
                </>
              ) : (
                <div className="text-center p-10">
                  <div className="w-20 h-20 bg-white/5 rounded-full flex items-center justify-center mx-auto mb-4 border border-white/10">
                    <svg className="w-10 h-10 text-white/20" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
                    </svg>
                  </div>
                  <p className="text-white/20 font-bold uppercase tracking-widest text-xs">Awaiting Imaging Data</p>
                </div>
              )}
            </div>
            {result?.caseId && (
              <div className="mt-4 px-6 py-2 bg-gray-100 rounded-full text-[10px] font-black text-gray-500 uppercase tracking-widest">
                Case Reference: {result.caseId}
              </div>
            )}
          </div>
        </div>
        
        {/* ── RESULTS ── */}
        {result && (
          <div className="mt-12 space-y-8">
            {result.confidence > 90 && result.prediction === 'Tumor' && (
              <div className="bg-burgundy text-white p-8 rounded-[2rem] shadow-2xl flex items-center gap-6 border-b-4 border-red-500">
                <div className="w-16 h-16 bg-white/10 rounded-full flex items-center justify-center shrink-0 border border-white/20">
                  <svg className="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2"
                      d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
                  </svg>
                </div>
                <div>
                  <h3 className="text-xl font-black uppercase mb-1">High-confidence abnormality detected (&gt;90%)</h3>
                  <p className="text-sm opacity-90">Seek medical attention promptly. Confirm with a qualified clinician.</p>
                </div>
              </div>
            )}

            <ResultSummaryCard prediction={result.prediction} confidence={result.confidence} />

            <div className="bg-white p-10 rounded-[2rem] shadow-sm border border-gray-100">
              <h4 className="text-xs font-black uppercase tracking-widest text-burgundy mb-4 flex items-center gap-2">
                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2"
                    d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
                AI Clinical Rationale
              </h4>
              <p className="text-gray-700 leading-relaxed italic font-medium">"{result.explanation}"</p>
              <div className="mt-8 flex flex-wrap gap-4">
                <button
                  onClick={() => handleDownloadReport(result)}
                  className="px-8 py-3 bg-burgundy text-white rounded-xl font-bold text-sm shadow-lg hover:shadow-xl transition"
                >
                  Download Formal Report
                </button>
                <button
                  onClick={resetScan}
                  className="px-8 py-3 border-2 border-gray-200 text-gray-600 rounded-xl font-bold text-sm hover:bg-gray-50 transition"
                >
                  New Scan
                </button>
              </div>
            </div>

            <ClinicalDisclaimer />
          </div>
        )}
      </div>

      {/* ── SCAN HISTORY ── */}
      <div className="bg-white rounded-[3rem] p-10 shadow-sm border border-gray-100">
        <h2 className="text-2xl font-black mb-8 text-gray-800">Historical Scan Record</h2>
        {scans.length === 0 ? (
          <div className="py-20 text-center">
            <p className="text-gray-400 font-bold italic">No previous diagnostic records found.</p>
            <p className="text-gray-300 text-xs mt-2">Records appear here after analysis is performed.</p>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {scans.map(scan => (
              <div key={scan.id} className="border border-gray-100 rounded-[2rem] overflow-hidden group hover:shadow-xl transition-all duration-500 bg-gray-50/30">
                <div className="h-48 bg-black flex items-center justify-center overflow-hidden">
                  {scan.mriUrl ? (
                    <img src={scan.mriUrl} className="w-full h-full object-cover group-hover:scale-110 transition duration-700" alt="Scan" />
                  ) : (
                    <p className="text-white/20 text-xs font-bold uppercase tracking-widest">No Image Stored</p>
                  )}
                </div>
                <div className="p-6">
                  <div className="flex justify-between items-start mb-4">
                    <span className="text-[10px] font-black text-gray-400 uppercase tracking-widest">
                      {new Date(scan.date).toLocaleDateString()}
                    </span>
                    <span className={`text-[9px] font-black uppercase px-3 py-1 rounded-full ${
                      scan.prediction === 'Tumor' ? 'bg-red-100 text-red-600' : 'bg-green-100 text-green-600'
                    }`}>
                      {scan.prediction}
                    </span>
                  </div>
                  <h4 className="text-sm font-black text-gray-800">{scan.caseId || `SCAN_${scan.id}`}</h4>
                  <p className="text-xs text-gray-500 font-medium mt-1">Confidence: {scan.confidence}%</p>
                  <button
                    onClick={() => handleDownloadReport(scan)}
                    className="mt-4 text-[10px] font-black text-burgundy uppercase border-b border-burgundy/20 pb-1 hover:opacity-70 transition"
                  >
                    Download Report
                  </button>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
};

export default PatientPortal;